version: "3.9"
services:
  console:
    build: "."
    environment:
      DB_URL: "Cake\\ElasticSearch\\Datasource\\Connection://elasticsearch:9200?driver=Cake\\ElasticSearch\\Datasource\\Connection"
    volumes:
      - .:/code
  elasticsearch:
    image: "elasticsearch:7.17.4"
    ports:
      - 9200/tcp
    environment:
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms500m -Xmx500m
    healthcheck:
      test: "curl -f http://127.0.0.1:9200/_cluster/health || exit 1"
      interval: "10s"
      timeout: "5s"
      retries: 10
      start_period: "30s"
